#!/usr/bin/env python3
"""
QA Sync Notion Dashboard
- QA 진행 현황 대시보드 자동 생성/업데이트
- 시나리오 완료율, 이슈 현황 시각화
- Claude Code Notion MCP와 연동
"""

import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

# 상태 관리자 임포트
sys.path.insert(0, str(Path(__file__).parent))
from state_manager import get_project, get_project_stats, list_projects, load_state


def generate_dashboard_markdown(project_name: str) -> str:
    """프로젝트 대시보드 마크다운 생성"""
    project = get_project(project_name)

    if not project:
        return f"# ❌ Project '{project_name}' not found"

    stats = project.get("stats", {})
    config = project.get("config", {})
    scenarios = project.get("scenarios", [])
    issues = project.get("issues_created", [])

    # 진행률 계산
    total_scenarios = stats.get("total_scenarios", 0)
    completed_scenarios = stats.get("completed_scenarios", 0)
    progress_pct = (completed_scenarios / total_scenarios * 100) if total_scenarios > 0 else 0

    # 프로그레스 바 생성
    progress_filled = int(progress_pct / 10)
    progress_bar = "█" * progress_filled + "░" * (10 - progress_filled)

    # 이슈 통계
    total_issues = stats.get("total_issues", 0)
    bugs = stats.get("bugs", 0)
    improvements = stats.get("improvements", 0)
    data_errors = stats.get("data_errors", 0)

    # 최근 이슈 (최근 5개)
    recent_issues = sorted(issues, key=lambda x: x.get("created_at", ""), reverse=True)[:5]

    md = f"""# 🎯 QA Dashboard: {project_name}

> 마지막 업데이트: {datetime.now().strftime('%Y-%m-%d %H:%M')}

---

## 📊 요약

| 항목 | 값 |
|------|-----|
| 사이트 | {config.get('site_url', 'N/A')} |
| Slack 채널 | {config.get('slack_channel', 'N/A')} |
| Linear 프로젝트 | {config.get('linear_project_url', 'N/A')} |

---

## 🏃 시나리오 진행률

```
{progress_bar} {progress_pct:.0f}%
```

**{completed_scenarios} / {total_scenarios}** 시나리오 완료

---

## 🐛 이슈 현황

| 유형 | 개수 | 비율 |
|------|------|------|
| 🐛 버그 | {bugs} | {bugs/total_issues*100:.0f}% |
| 💡 개선 | {improvements} | {improvements/total_issues*100:.0f}% |
| 📊 데이터 | {data_errors} | {data_errors/total_issues*100:.0f}% |
| **합계** | **{total_issues}** | 100% |

""" if total_issues > 0 else f"""# 🎯 QA Dashboard: {project_name}

> 마지막 업데이트: {datetime.now().strftime('%Y-%m-%d %H:%M')}

---

## 📊 요약

| 항목 | 값 |
|------|-----|
| 사이트 | {config.get('site_url', 'N/A')} |
| Slack 채널 | {config.get('slack_channel', 'N/A')} |
| Linear 프로젝트 | {config.get('linear_project_url', 'N/A')} |

---

## 🏃 시나리오 진행률

```
{progress_bar} {progress_pct:.0f}%
```

**{completed_scenarios} / {total_scenarios}** 시나리오 완료

---

## 🐛 이슈 현황

아직 등록된 이슈가 없습니다.

"""

    # 최근 이슈 섹션 추가
    if recent_issues:
        md += "---\n\n## 📋 최근 이슈\n\n"
        md += "| 시간 | 유형 | ID |\n|------|------|----|\n"
        for issue in recent_issues:
            created = issue.get("created_at", "")[:16].replace("T", " ")
            issue_type = {"bug": "🐛", "improvement": "💡", "data_error": "📊"}.get(issue.get("issue_type"), "❓")
            md += f"| {created} | {issue_type} | {issue.get('issue_id', 'N/A')} |\n"

    # 시나리오 목록 (미완료 우선)
    if scenarios:
        incomplete = [s for s in scenarios if not s.get("completed", False)]
        complete = [s for s in scenarios if s.get("completed", False)]

        md += "\n---\n\n## 📝 시나리오 목록\n\n"

        if incomplete:
            md += "### ⏳ 미완료\n\n"
            md += "| # | 유형 | 시나리오 | 확인 사항 |\n|---|------|---------|----------|\n"
            for i, s in enumerate(incomplete[:10], 1):
                md += f"| {i} | {s.get('type', '')} | {s.get('scenario', '')[:30]} | {s.get('check', '')[:30]} |\n"
            if len(incomplete) > 10:
                md += f"\n... 외 {len(incomplete) - 10}개\n"

        if complete:
            md += "\n### ✅ 완료\n\n"
            md += "| # | 유형 | 시나리오 | 완료일 |\n|---|------|---------|--------|\n"
            for i, s in enumerate(complete[:5], 1):
                completed_at = s.get("completed_at", "")[:10]
                md += f"| {i} | {s.get('type', '')} | {s.get('scenario', '')[:30]} | {completed_at} |\n"
            if len(complete) > 5:
                md += f"\n... 외 {len(complete) - 5}개\n"

    md += "\n---\n\n*Generated by QA Sync*"

    return md


def generate_summary_dashboard() -> str:
    """전체 프로젝트 요약 대시보드"""
    state = load_state()
    projects = state.get("projects", {})

    if not projects:
        return "# QA Dashboard\n\n프로젝트가 없습니다."

    md = f"""# 🎯 QA Dashboard

> 마지막 업데이트: {datetime.now().strftime('%Y-%m-%d %H:%M')}

---

## 📊 프로젝트 현황

| 프로젝트 | 시나리오 | 이슈 | 버그 | 개선 | 데이터 |
|----------|----------|------|------|------|--------|
"""

    total_scenarios = 0
    total_issues = 0

    for name, project in projects.items():
        stats = project.get("stats", {})
        scenarios = f"{stats.get('completed_scenarios', 0)}/{stats.get('total_scenarios', 0)}"
        issues = stats.get("total_issues", 0)
        bugs = stats.get("bugs", 0)
        improvements = stats.get("improvements", 0)
        data_errors = stats.get("data_errors", 0)

        md += f"| {name} | {scenarios} | {issues} | {bugs} | {improvements} | {data_errors} |\n"

        total_scenarios += stats.get("total_scenarios", 0)
        total_issues += issues

    md += f"\n**전체: {len(projects)}개 프로젝트, {total_scenarios}개 시나리오, {total_issues}개 이슈**\n"

    md += "\n---\n\n*Generated by QA Sync*"

    return md


def export_to_file(project_name: Optional[str], output_path: str):
    """대시보드를 파일로 내보내기"""
    if project_name:
        content = generate_dashboard_markdown(project_name)
    else:
        content = generate_summary_dashboard()

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Dashboard exported to: {output_path}")


def print_notion_instructions(project_name: Optional[str] = None):
    """Notion 업데이트 방법 안내"""
    if project_name:
        content = generate_dashboard_markdown(project_name)
    else:
        content = generate_summary_dashboard()

    print("=" * 60)
    print("NOTION DASHBOARD CONTENT")
    print("=" * 60)
    print()
    print("Claude Code에서 다음 명령어로 Notion에 업데이트:")
    print()
    print('1. 기존 페이지 업데이트:')
    print('   mcp__notion__notion-update-page 사용')
    print()
    print('2. 새 페이지 생성:')
    print('   mcp__notion__notion-create-pages 사용')
    print()
    print("=" * 60)
    print()
    print(content)


# CLI 인터페이스
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: notion_dashboard.py <command> [args]")
        print("")
        print("Commands:")
        print("  show [project_name]      - 대시보드 출력 (전체 또는 특정 프로젝트)")
        print("  export <output_path> [project_name] - 마크다운 파일로 내보내기")
        print("  notion [project_name]    - Notion 업데이트 안내")
        print("  list                     - 프로젝트 목록")
        print("")
        print("Example:")
        print("  python3 notion_dashboard.py show valley-v2")
        print("  python3 notion_dashboard.py export ./dashboard.md")
        sys.exit(1)

    cmd = sys.argv[1]

    if cmd == "list":
        projects = list_projects()
        if projects:
            print("Available projects:")
            for p in projects:
                print(f"  - {p}")
        else:
            print("No projects found.")

    elif cmd == "show":
        project_name = sys.argv[2] if len(sys.argv) > 2 else None
        if project_name:
            print(generate_dashboard_markdown(project_name))
        else:
            print(generate_summary_dashboard())

    elif cmd == "export" and len(sys.argv) > 2:
        output_path = sys.argv[2]
        project_name = sys.argv[3] if len(sys.argv) > 3 else None
        export_to_file(project_name, output_path)

    elif cmd == "notion":
        project_name = sys.argv[2] if len(sys.argv) > 2 else None
        print_notion_instructions(project_name)

    else:
        print(f"Unknown command: {cmd}")
        sys.exit(1)
